<?php

$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
if ($_productCollection->count()):
    $_iterator = 1;
    ?>
    <div class="category-products">
        <div class="yt-products-container clearfix">
        <div class="products-grid">
        <div class="row">
            <?php foreach ($_productCollection as $_product): ?>
            <?php
            //var_dump($_product->getSmallImage());die;
            $now = date("Y-m-d H:m:s");
            $newsFrom = $_product->getNewsFromDate();
            $newsTo = $_product->getNewsToDate();
            $specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice();
            $price = Mage::getModel('catalog/product')->load($_product->getId())->getPrice();
            //$saleoff= round(($price - $specialprice)/$price*100) ;
            $special_from_date = $_product->getSpecialFromDate();
            $special_to_date = $_product->getSpecialToDate();
            ?>
            <div class="item col-lg-2 col-md-2 col-sm-4 col-xs-12">
                <div class="item-inner">

                    <div class="product-image">
                        <a href="<?php echo $_product->getProductUrl() ?>" class="product-img"
                           title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                            <?php
                            if ($_product->getThumbnail() != $_product->getSmallImage()) {
                                ?>
                                <img class="small-image"
                                     src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(270, 270); ?>"
                                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                                <img class="thumnail-image image-hover"
                                     src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(270, 270) ?>"
                                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'thumbnail'), null, true) ?>"/>                            <?php } else { ?>
                                <img class="small-image"
                                     src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(270, 270); ?>"
                                     alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
                            <?php } ?>
                        </a>
                        <?php if ($now >= $newsFrom && $now <= $newsTo) { ?>
                            <span class="new-product have-ico"><?php echo $this->__('New'); ?></span>
                        <?php
                        }
                        if ($specialprice) {
                            ?>
                            <span class="sale-product have-ico"><?php echo $this->__('Sale'); ?></span>
                        <?php } ?>
                    </div>

                    <div class="product-info">
                        <div class="product-name">
                            <a href="<?php echo $_product->getProductUrl() ?>"
                               title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                                <?php if (strlen($_helper->productAttribute($_product, $_product->getName(), 'name')) > 100) {
                                    echo substr($_helper->productAttribute($_product, $_product->getName(), 'name'), 0, 100);
                                } else {
                                    echo $_helper->productAttribute($_product, $_product->getName(), 'name');
                                }?>
                            </a>
                        </div>
                        <div class="product-review">
                            <?php echo $this->getReviewsSummaryHtml($_product, "short", true); ?>
                        </div>
                        <div class="product-price">
                            <?php echo $this->getPriceHtml($_product, true) ?>
                        </div>

                        <div class="product-addto-wrap">
                            <div class="product-addcart">
                                <?php if ($_product->isSaleable()): ?>

                                    <a class="btn-cart" title="<?php echo $this->__('Add to cart') ?>"
                                       href="javascript:void(0);"
                                       onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                        <?php echo $this->__('Add to Cart') ?>
                                    </a>

                                <?php else: ?>
                                    <p class="availability out-of-stock">
                                        <span><?php echo $this->__('Out of stock') ?> </span>
                                    </p>
                                <?php endif; ?>
                            </div>
                            <div class="wishlist-compare">
                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <a class="link-wishlist"
                                       href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"
                                       title="<?php echo $this->__('Add to Wishlist') ?>">
                                        <?php echo $this->__('Add to Wishlist') ?>
                                    </a>
                                <?php endif; ?>

                                <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>

                                    <a class="link-compare" href="<?php echo $_compareUrl ?>"
                                       title="<?php echo $this->__('Add to Compare'); ?>">
                                        <?php echo $this->__('Add to Compare') ?>
                                    </a>

                                <?php endif; ?>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
            <?php if ($_iterator % 6 == 0 && $_iterator != $_productCollection->count()): ?>
        </div>
        <div class="row">
            <?php endif; ?>
            <?php $_iterator++;
            endforeach; ?>
        </div>
        </div>
        </div>
    </div>
<?php endif; ?>